export const FETCH_TRENDING_MOVIE_PENDING = 'FETCH_TRENDING_MOVIE_PENDING';
export const FETCH_TRENDING_MOVIE_SUCCESS = 'FETCH_TRENDING_MOVIE_SUCCESS';
export const FETCH_TRENDING_MOVIE_ERROR = 'FETCH_TRENDING_MOVIE_ERROR';

export const FETCH_DETAIL_MOVIE_PENDING = 'FETCH_DETAIL_MOVIE_PENDING';
export const FETCH_DETAIL_MOVIE_SUCCESS = 'FETCH_DETAIL_MOVIE_SUCCESS';
export const FETCH_DETAIL_MOVIE_ERROR = 'FETCH_DETAIL_MOVIE_ERROR';

export const FETCH_CATEGORY_MOVIE_PENDING = 'FETCH_CATEGORY_MOVIE_PENDING';
export const FETCH_CATEGORY_MOVIE_SUCCESS = 'FETCH_CATEGORY_MOVIE_SUCCESS';
export const FETCH_CATEGORY_MOVIE_ERROR = 'FETCH_CATEGORY_MOVIE_ERROR';

export const FETCH_SEARCH_MOVIE_PENDING = 'FETCH_SEARCH_MOVIE_PENDING';
export const FETCH_SEARCH_MOVIE_SUCCESS = 'FETCH_SEARCH_MOVIE_SUCCESS';
export const FETCH_SEARCH_MOVIE_ERROR = 'FETCH_SEARCH_MOVIE_ERROR';
